import { Applicant } from './models/applicant';

export const ALL_APPLICANTS: Applicant[] = [
  {
    firstName: 'Mette',
    lastName: 'Vuns',
    age: 17,
    image: 'http://api.randomuser.me/portraits/women/91.jpg',
    rating: 5,
    noOfAttachments: 3,
    isFavorite: true,
    applicationDate: new Date('Dec 08 2019 07:44:57'),
    noOfOther: 2,
  },
  {
    firstName: 'Peter P.',
    lastName: 'Dahl',
    age: 28,
    image: 'http://api.randomuser.me/portraits/men/93.jpg',
    rating: 1,
    noOfAttachments: 3,
    isFavorite: true,
    applicationDate: new Date('Oct 03 2017 14:44:57'),
    noOfOther: 2,
  },
  {
    firstName: 'Buzz',
    lastName: 'Lait-tjir',
    age: 28,
    image: 'http://api.randomuser.me/portraits/men/94.jpg',
    rating: 5,
    noOfAttachments: 3,
    isFavorite: true,
    applicationDate: new Date('Jan 01 2019 07:44:57'),
    noOfOther: 2,
  },
  {
    firstName: 'Kresten',
    lastName: 'Domm',
    age: 28,
    image: 'http://api.randomuser.me/portraits/men/14.jpg',
    rating: 0,
    noOfAttachments: 3,
    isFavorite: true,
    applicationDate: new Date('Jan 01 2019 07:44:57'),
    noOfOther: 2,
  },
  {
    firstName: 'Volkan',
    lastName: 'Lawa',
    age: 28,
    image: 'http://api.randomuser.me/portraits/men/4.jpg',
    rating: 4,
    noOfAttachments: 3,
    isFavorite: true,
    applicationDate: new Date('Jan 01 2019 07:44:57'),
    noOfOther: 2,
  },
  {
    firstName: 'Kim',
    lastName: 'Pårs-ibel',
    age: 14,
    image: 'http://api.randomuser.me/portraits/men/8.jpg',
    rating: 2,
    noOfAttachments: 3,
    isFavorite: true,
    applicationDate: new Date('Jan 01 2019 07:44:57'),
    noOfOther: 2,
  },
];